This is a Jupyter book for test 'Python for data analysis' of chapter6

reference data

something,a,b,c,d,message
one,1,2,3,4,
two,5,6,,8,world
three,NULL,10,11,12,foo

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

In [3]:
csvPath = Path('data.csv')
result = pd.read_csv(csvPath)
print(result)
result.isna()

  something    a   b     c   d message
0       one  1.0   2   3.0   4     NaN
1       two  5.0   6   NaN   8   world
2     three  NaN  10  11.0  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False   True  False  False  False    False

In [ ]:
csvPath = Path('data.csv')
result = pd.read_csv(csvPath, na_values=["NULL"])
print(result)
result.isna()

  something    a   b     c   d message
0       one  1.0   2   3.0   4     NaN
1       two  5.0   6   NaN   8   world
2     three  NaN  10  11.0  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False   True  False  False  False    False

In [5]:
csvPath = Path('data.csv')
result = pd.read_csv(csvPath,keep_default_na=False)
print(result)
result.isna()

  something     a   b   c   d message
0       one     1   2   3   4
1       two     5   6       8   world
2     three  NULL  10  11  12     foo

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [6]:
csvPath = Path('data.csv')
sentinels = {'message':['foo', 'NA'], 'something':['two']}
result = pd.read_csv(csvPath, na_values=sentinels,keep_default_na=False)
print(result)
result.isna()

  something     a   b   c   d message
0       one     1   2   3   4
1       NaN     5   6       8   world
2     three  NULL  10  11  12     NaN

   something      a      b      c      d  message
0      False  False  False  False  False    False
1       True  False  False  False  False    False
2      False  False  False  False  False     True